### ISSUE TITLE
Scripts fails on Google Picasa Error

### ISSUE THREAD

**Issue by sebastianw** [sebastianw/gallery2picasa#1]
Traceback (most recent call last):
File "./gallery2picasa.py", line 107, in
main(sys.argv)
File "./gallery2picasa.py", line 101, in main
summary, filename, keywords=keywords)
File "/usr/lib/pymodules/python2.6/gdata/photos/service.py", line 470, in InsertPhotoSimple
content_type)
File "/usr/lib/pymodules/python2.6/gdata/photos/service.py", line 428, in InsertPhoto
raise GooglePhotosException(e.args[0])
gdata.photos.service.GooglePhotosException: (500, 'Internal Server Error', 'Error: 10 STORAGE_UNAVAIL')

Traceback (most recent call last):
File "./gallery2picasa.py", line 107, in
main(sys.argv)
File "./gallery2picasa.py", line 101, in main
summary, filename, keywords=keywords)
File "/usr/lib/pymodules/python2.6/gdata/photos/service.py", line 470, in InsertPhotoSimple
content_type)
File "/usr/lib/pymodules/python2.6/gdata/photos/service.py", line 428, in InsertPhoto
raise GooglePhotosException(e.args[0])
gdata.photos.service.GooglePhotosException: (500, 'Internal Server Error', 'server is not responding')

**Comment by sebastianw** [comment]
@baastrup Here is the issue for this problem
