### ISSUE TITLE
filename_or_handle must be a path name or a file-like object

### ISSUE THREAD

**Issue by sandernaudts** [sebastianw/gallery2picasa#22]
I'm getting the following error immediately after saying "a" to upload all albums

:~/gtop/sebastianw-gallery2picasa-ef4259c# ./gallery2picasa.py -d naudtson -b root -t ng_ -u XXXX -g /homez.312/naudtson/g2data/
DB Password:
Google Password:
Upload Album "Gallery - 2004 - Corsica"? [y/N/a]a

CREATING ALBUM [Corsica] []
        CREATING Item [F:IMG00001.JPG] [T:IMG00001.JPG] [S:IMG00001.JPG] [K:]
Traceback (most recent call last):
  File "./gallery2picasa.py", line 275, in <module>
    main(sys.argv)
  File "./gallery2picasa.py", line 262, in main
    raise e
gdata.photos.service.GooglePhotosException: (601, "Found <type 'unicode'>, not path name or object with a .read() method", '`filename_or_handle` must be a path name or a file-like object')

**Comment by sandernaudts** [comment]
g2data folder corrupt after wget download. Issue fixed
