### ISSUE TITLE
Google error: Entity too large!

### ISSUE THREAD

**Issue by ghost** [sebastianw/gallery2picasa#8]
Im still getting the following error with the newst script, seems to bee if there is more that on too large file in a row

Google error: Entity too large!
        CREATING Item [F:Billede 127.avi] [T:Billede 127] [S:Billede 127] [K:]
        CREATING Item [F:MVI_0509.avi] [T:MVI_0509] [S:MVI_0509] [K:]
Google error: Entity too large!
        CREATING Item [F:MVI_0512.avi] [T:MVI_0512] [S:MVI_0512] [K:]
        CREATING Item [F:MVI_0589.avi] [T:MVI_0589] [S:MVI_0589] [K:]
        CREATING Item [F:MVI_0591.avi] [T:MVI_0591] [S:MVI_0591] [K:]
Google error: Entity too large!
        CREATING Item [F:MVI_0592.avi] [T:MVI_0592] [S:MVI_0592] [K:]
        CREATING Item [F:MVI_0593.avi] [T:MVI_0593] [S:MVI_0593] [K:]
Google error: Entity too large!
        CREATING Item [F:Nyt01_10 014.avi] [T:Nyt01.10 014] [S:Nyt01.10 014] [K:]
Traceback (most recent call last):
  File "./gallery2picasa.py", line 225, in <module>
    main(sys.argv)
  File "./gallery2picasa.py", line 197, in main
    summary, filename, keywords=keywords, content_type=filetype)
  File "/usr/lib/pymodules/python2.6/gdata/photos/service.py", line 470, in InsertPhotoSimple
    content_type)
  File "/usr/lib/pymodules/python2.6/gdata/photos/service.py", line 426, in InsertPhoto
    converter=gdata.photos.PhotoEntryFromString)
  File "/usr/lib/pymodules/python2.6/gdata/service.py", line 1235, in Post
    media_source=media_source, converter=converter)
  File "/usr/lib/pymodules/python2.6/gdata/service.py", line 1302, in PostOrPut
    multipart[2]], headers=extra_headers, url_params=url_params)
  File "/usr/lib/pymodules/python2.6/atom/**init**.py", line 92, in optional_warn_function
    return f(_args, *_kwargs)
  File "/usr/lib/pymodules/python2.6/atom/service.py", line 185, in request
    data=data, headers=all_headers)
  File "/usr/lib/pymodules/python2.6/gdata/auth.py", line 725, in perform_request
    return http_client.request(operation, url, data=data, headers=headers)
  File "/usr/lib/pymodules/python2.6/atom/http.py", line 169, in request
    _send_data_part(data_part, connection)
  File "/usr/lib/pymodules/python2.6/atom/http.py", line 358, in _send_data_part
    connection.send(binarydata)
  File "/usr/lib/python2.6/httplib.py", line 743, in send
    self.sock.sendall(str)
  File "/usr/lib/python2.6/ssl.py", line 203, in sendall
    v = self.send(data[count:])
  File "/usr/lib/python2.6/ssl.py", line 94, in <lambda>
    self.send = lambda data, flags=0: SSLSocket.send(self, data, flags)
  File "/usr/lib/python2.6/ssl.py", line 174, in send
    v = self._sslobj.write(data)
socket.error: [Errno 32] Broken pipe

**Comment by ghost** [comment]
This could maybe be do to the new rules after google plus is lunched, where you can upload 15 min video.

**Comment by sebastianw** [comment]
That's an error from the socket, it seems that the connection is dropped. It could be some sort of DoS prevention from Google. I think you would have to exclude the bigger videos and try the upload without them.

**Comment by ghost** [comment]
aah ok, would it be possible to make an option to exclude videos then?
so if this script fails you can choose not to include videos.
